# 20 Functions in Numpy

In [1]:
import numpy as np

# 1. Creating an Array

In [2]:
np.array([0,15])

array([ 0, 15])

In [3]:
x = np.array([0,1,2,3])
print(x)

[0 1 2 3]


In [4]:
y = np.array([[0,1,2],[4,5,6]])
print(y)

[[0 1 2]
 [4 5 6]]


In [5]:
z = np.array([[[0,1,2],[3,4,5],[6,7,8]]])
print(z)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


# 2. Function for getting the dimension of arrays 

In [6]:
x.ndim

1

In [7]:
y.ndim

2

In [8]:
z.ndim

3

# 3. Shape of Array

In [9]:
x.shape

(4,)

In [10]:
y.shape

(2, 3)

In [11]:
z.shape

(1, 3, 3)

## 4. Size of the Arrays

In [12]:
x.itemsize

4

In [13]:
y.itemsize

4

In [14]:
z.itemsize

4

## 5. Getting Type of Array

In [15]:
x.dtype

dtype('int32')

In [16]:
y.dtype

dtype('int32')

In [17]:
z.dtype

dtype('int32')

## 6. Creating all 1s Matrix

In [18]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

 ## 7. Creating all Zero Matrix

In [19]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 8. Getting total size of Array

In [20]:
x.nbytes

16

In [21]:
y.nbytes

24

In [22]:
z.nbytes

36

### 9. Arrange: Returns evenly spaced values within a given interval

In [23]:
a = np.arange(0,26)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [24]:
b = np.arange(0,26,5)
b

array([ 0,  5, 10, 15, 20, 25])

## 10. Random Decimal Numbers

In [25]:
np.random.rand(4,3)

array([[0.24553316, 0.31002159, 0.05650948],
       [0.52433101, 0.74875988, 0.21812621],
       [0.85672684, 0.49856949, 0.16357498],
       [0.45411425, 0.77906222, 0.1194012 ]])

## 11. Random Interger Values

In [26]:
w = np.random.randint(-1,9, size =(3,3))
w

array([[4, 3, 3],
       [4, 7, 6],
       [4, 0, 8]])

In [27]:
w.shape

(3, 3)

### 12. Identity matrix

In [28]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 13. Repeating array

In [29]:
arr = np.array([[1,2,4]])
A1 = np.repeat(arr,3, axis = 0)
print(A1)

[[1 2 4]
 [1 2 4]
 [1 2 4]]


## 14.Linspace: Return evenly spaced numbers over a specified interval.

In [30]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [31]:
np.linspace(0,24,3)

array([ 0., 12., 24.])

## 15 Eye: Another method of printing identity matrix

In [32]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [33]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.eye(6,6,1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

## 16 Minimum Value

In [35]:
y.min()

0

## 17 Maximum Value

In [36]:
z.max()

8

## 18 Copying arrays

In [37]:
u = np.array([1,2,3,4,5,6])
v = u
print(v)

[1 2 3 4 5 6]


## 19. Appending Arrays

In [38]:
print("Original array")
numbers = np.arange(8)
print(numbers)
print("\n")
print("Array with appended values at the end")

Original array
[0 1 2 3 4 5 6 7]


Array with appended values at the end


In [39]:
print("Original array")
q = np.arange(2,11).reshape (3,3)
print(q)
print("\n")
print("Arrays with appended values at the end")
print(np.append(q, [[12,13,14]], axis = 0))

Original array
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Arrays with appended values at the end
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [12 13 14]]


### 20 Printing all boarders 1s and 0s inside

In [40]:
print("Original array")
array_2d = np.ones((6,6))
print(array_2d)
print("\n")
print("Arrays with one on the boarder and zeros inside")
array_2d[1:-1,1:-1] = 0
print(array_2d)

Original array
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


Arrays with one on the boarder and zeros inside
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


# 20 FUNCTIONS IN PANDAS

In [41]:
import pandas as pd

#### 1. Creating a table from the scratch  using dictionary

In [42]:
Table = {"Names": ["Chinaza", "Happiness", "Terry", "Vazir", "Malakh"],
        "Age":[21, 24, 30, 10, 8],
        "States": ["Abia", "Lagos", "Nasarawa", "Abuja", "Rivers"]}

In [43]:
data_frame = pd.DataFrame(Table)
data_frame

Names  Age    States
0    Chinaza   21      Abia
1  Happiness   24     Lagos
2      Terry   30  Nasarawa
3      Vazir   10     Abuja
4     Malakh    8    Rivers

### 2. Mean: Return the mean of the values over the requested axis.

In [44]:
df["Age"].mean()

NameError: name 'df' is not defined

### 3. Sum: Return the sum of the values over the requested axis.


In [ ]:
df["Age"].sum ()

In [ ]:
df["Age"][:2].sum()

### 4. Max: Return the maximum of the values over the requested axis.

In [ ]:
df["Age"].max()

### 5. Min: Return the minimum of the values over the requested axis.


In [ ]:
df["Age"].min()

### 6. Count: Count non-NA cells for each column or row.

In [ ]:
df["Age"].count()

### 7. df.columns: Used to find the columns on the table

In [ ]:
df.columns

### 8. Loc: Access a group of rows and columns by label(s) or a boolean array.

In [ ]:
df.loc[1]

In [ ]:
df.loc[0:3, "Names"]

### 9. iloc: Purely integer-location based indexing for selection by position.


In [ ]:
df.iloc[0:2]

### 10. Where: Replace values where the condition is False.

In [ ]:
# method chaining (Equivalance of sumif)
df["Age"].where(df["Age"]>20).sum()

#### 11. Value_counts: Return a Series containing counts of unique rows in the DataFrame.


In [ ]:
# method chain (Equivalance of countif)
df["Age"].where(df["Age"]>20).value_counts()

In [ ]:
df["Age"].where(df["Age"]<20).value_counts().sum()

### 12. Count: Count non-NA cells for each column or row.

In [ ]:
df["Age"].where(df["Age"]<20).count()

### 13. pd.read: Read an Excel file into a pandas DataFrame.

In [ ]:
df = pd.read_csv('googleplaystore.csv')
df

### 14. head: This function returns the first `n` rows for the object based on position. 

In [ ]:
df.head()

### 15. info: Print a concise summary of a DataFrame.

In [ ]:
df.info()

### 16. Shape: Return a tuple representing the dimensionality of the DataFrame.

In [ ]:
df.shape

### 17. Size: Return an int representing the number of elements in this object.

In [ ]:
df.size

### 18. Sample: Return a random sample of items from an axis of object.

In [ ]:
df.sample(n=5)

### 19. Describe: Generate descriptive statistics.Descriptive statistics include those that summarize the central


In [ ]:
df.describe()

In [ ]:
# For Transposing
df.describe().T

### 20. nunique: Count number of distinct elements in specified axis.

In [ ]:
df.nunique()